### ISSUE TITLE
Handle non UTF-8 encoding in source CSVs

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#57]
Currently, the Co-ops UK organizations data includes a few rows like this:
```
"R007626","31650R","FCA","Film Caf� Co-op Limited","Film Caf� Co-op","Society","206 Corfield Street","London","Tower Hamlets","E2 0DP","England","UKSIC07-59","Information and Communication","UKSIC07-59","Motion picture, video and television programme production, sound recording and music publishing activities","","","","","","","Digital, Media and Communication","Self-employed","Live","25/6/2012",""
```
These cause problems when the HTML is generated. An exception is raised:
```
#<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT>
```
Here's a backtrace:
```
/Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:34:in `block (2 levels) in html': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/utils/xml.rb:15:in `xml'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:25:in `block in html'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/utils/xml.rb:15:in `xml'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:21:in `html'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:17:in `block in save'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:17:in `open'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:17:in `save'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/collection.rb:33:in `block in serialize_everything'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/collection.rb:30:in `each'
	from /Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/collection.rb:30:in `serialize_everything'
	from ../../tools/se_open_data/bin/csv/standard/csv-to-rdf.rb:80:in `<main>'
```
Where `/Users/matt/SEA/open-data-and-maps/data/tools/se_open_data/lib/se_open_data/initiative/html.rb:34` is:
```
	    html_fragment_for_inserted_code("RDF/XML serialization", rdf_file) +
```

**Comment by matt-wallis** [comment]
The most recent commit is a temporary workaround, so this is not urgent to fix.

**Comment by matt-wallis** [comment]
Read this: http://ruby-doc.org/core-2.4.0/Encoding.html

**Comment by matt-wallis** [comment]
Interesting article: [CSV: An Encoding Nightmare](https://donatstudios.com/CSV-An-Encoding-Nightmare). Somewhere in there may lie the solution ...

**Comment by matt-wallis** [comment]
In conclusion: the source of the problem was in the way RDF files were being read, when they are to be placed in `<pre>` tags for the generated HTML for each initiative.
They were being read as binary (doh!), but they are in fact UTF-8 encoded text. The result was that when the RDF included any characters that were not ASCII-7bit, they were interpreted as ASCII-8 bit when the (binary) bytes were converted to a String.
